//activity related information object
export const activityDataObject = {
  sleep:"When we give the brain the rest it needs, we consolidate learning and recover from the experiences of the day.getting enough sleep can help keep our immune systems healthy and reduces risk of developing certain chronic health conditions. The National Sleep Foundation recommends that adults get 7 to 9 hours of sleep per night. Not allocating enough sleep time can lead to fatigue, poor concentration, increased stress, anxiety, and irritability",
  focus:"When we closely focus on tasks in a goal-oriented way, we take on challenges that make deep connections in the brain.Focus help to reduce stress and anxiety levels. it is recommended to allocate undisturbed period which is usaally between 1-3 hours daily to improve cognitive functioning and mental well-being.when it is ignored during daily activities, it can lead to decreased productivity, difficulty forming meaningful connections, and poorer mental health.",
  play:"When we allow ourselves to be spontaneous or creative, playfully enjoying novel experiences, we help make new connections in the brain.it is recomended to allocate at least 30 minutes daily.it can help to stimulate the mind and increase problem-solving abilities, creative thinking, and overall mental well-being. Play Time also helps reduce stress and increase happiness and satisfaction.However, when Play Time is ignored during daily activities, it can lead to feelings of boredom, mental fatigue, and difficulty concentrating on tasks. " ,
  timein:"When we quietly reflect internally, focusing on sensations, images, feelings and thoughts, we help to better integrate the brain.The recommended amount of time to dedicate to time-in is at least 10 minutes daily. Time-in is an essential aspect of the efforts to develop a healthy mental status since it helps the brain to recharge can it also boost creativity and productivity.When time-in is ignored during daily activities, it can lead to feelings of burnout and overwhelm, which can have a detrimental effect on both physical and mental health",
  downtime:"When we are non-focused, without any specific goal, and let our mind wander or simply relax, we help the brain recharge.Mind Platter recommends 20 to 30 minutes of daily relaxation. For instance, downtime could involve reading, listening to music, or walking in nature. If ignored, stress and burnout can result",
  coneccting:"When we connect with other people, ideally in person, and when we take time to appreciate our connection to the natural world around us, we activate and reinforce the brain's relational circuitry.at least 30 minutes should be set aside each day for connecting time activities like talking to someone, having a meaningful conversation, or going for a walk it helps in boosting creativity and productivity ",
  physical:"When we move our bodies, aerobically if medically possible, we strengthen the brain in many ways.it is recomended to allocate at least 30 minutes daily  to improve physical and mental well-being,increased energey level,improved concentration and enhance stress relief.",
}